import { StyleSheet, Dimensions } from 'react-native';

const { width, height } = Dimensions.get('window');

export const globalStyles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#fff',
  },
  inputExpandible: {
    flex: 1,
    borderWidth: 1,
    borderColor: '#ccc',
    paddingVertical: 8,
    paddingHorizontal: 12,
    borderRadius: 25,
    backgroundColor: '#f0f0f0',
    fontSize: 16,
  },
  searchRow: {
    flexDirection: 'row',
    alignItems: 'center',
    marginHorizontal: 10,
    marginTop: height * 0.05,
    backgroundColor: '#f2f2f2',
    borderRadius: 25,
    paddingHorizontal: 10,
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    zIndex: 1001,
  },
  searchIcon: {
    fontSize: 20,
    marginRight: 5,
  },
  clearIcon: {
    fontSize: 18,
    marginLeft: 8,
    color: '#666',
  },
  categoriaBoton: {
    backgroundColor: '#2b2b2b',
    borderRadius: 25,
    height: 40,
    paddingHorizontal: 12,
    marginRight: 8,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
  },
  categoriaBotonActivo: {
    backgroundColor: '#1f1f1f',
  },
  categoriaTexto: {
    color: '#fff',
    fontWeight: '500',
    fontSize: 14,
    paddingHorizontal: 4,
  },
  itemSugerencia: {
    padding: 12,
    backgroundColor: '#f9f9f9',
    borderBottomWidth: 1,
    borderBottomColor: '#ddd',
  },
  mensajeTexto: {
  position: 'absolute',
  bottom: 150,
  left: 0,
  right: 0,
  textAlign: 'center',
  color: '#C0DF85',
  fontWeight: 'bold',
  fontSize: 16,
  backgroundColor: 'rgba(0, 0, 0, 0.4)',
  paddingVertical: 6,
  marginHorizontal: 20,
  borderRadius: 10,
  zIndex: 1000,
  },
  mensajeEsperando: {
    textAlign: 'center',
    marginVertical: 20,
    color: 'gray',
  },
  floatingResults: {
    position: 'absolute',
    top: height * 0.12,
    left: 10,
    right: 10,
    maxHeight: 200,
    backgroundColor: '#C0DF85',
    borderRadius: 12,
    elevation: 5,
    shadowColor: '#C0DF85',
    shadowOpacity: 0.2,
    shadowOffset: { width: 0, height: 4 },
    shadowRadius: 6,
    zIndex: 1000,
  },
  floatingCategorias: {
    position: 'absolute',
    bottom: height * 0.12,
    left: 10,
    right: 10,
    paddingVertical: 6,
    paddingHorizontal: 8,
    backgroundColor: '#7DDF64',
    borderRadius: 20,
    elevation: 5,
    shadowColor: '#ED4D6E',
    shadowOpacity: 0.15,
    shadowOffset: { width: 0, height: 4 },
    shadowRadius: 6,
    zIndex: 999,
  },
});
